global:
  marketplace-ami: true
  owner: quickstart-eng@amazon.com
  qsname: quickstart-data-lake-wandisco
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  quickstart-data-lake-wandiscot1:
    parameter_input: quickstart-data-lake-wandisco-main.json
    template_file: quickstart-data-lake-wandisco-main.template
